doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    types:
      user_id: FC\Infrastructure\Mapping\User\UserIdType
      board_id: FC\Infrastructure\Mapping\Board\BoardIdType
      member_id: FC\Infrastructure\Mapping\Board\MemberIdType
      category_id: FC\Infrastructure\Mapping\Category\CategoryIdType
      tag_id: FC\Infrastructure\Mapping\Tag\TagIdType
      card_id: FC\Infrastructure\Mapping\Card\CardIdType

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '13'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      User:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Infrastructure/Mapping/User'
        prefix: 'FC\Domain\Aggregate\UserAggregate'
        alias: FC

      Board:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Infrastructure/Mapping/Board'
        prefix: 'FC\Domain\Aggregate\BoardAggregate'
        alias: FC

      Category:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Infrastructure/Mapping/Category'
        prefix: 'FC\Domain\Aggregate\CategoryAggregate'
        alias: FC

      Tag:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Infrastructure/Mapping/Tag'
        prefix: 'FC\Domain\Aggregate\TagAggregate'
        alias: FC

      Card:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Infrastructure/Mapping/Card'
        prefix: 'FC\Domain\Aggregate\CardAggregate'
        alias: FC

      ValueObject:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Infrastructure/Mapping/ValueObject'
        prefix: 'FC\Domain\ValueObject'
        alias: FC
