doctrine_migrations:
  migrations_paths:
    # namespace is arbitrary but should be different from App\Migrations
    # as migrations classes should NOT be autoloaded
    FC\Infrastructure\Migrations: '%kernel.project_dir%/src/Infrastructure/Migrations'
  enable_profiler: '%kernel.debug%'
