services:
  _defaults:
    autowire: true
    autoconfigure: true

  FC\Application\Query\Board\BoardListQueryHandler:
    tags: [ { name: messenger.message_handler, bus: query.bus } ]
    autoconfigure: false
