services:
  _defaults:
    autowire: true
    autoconfigure: true

  FC\Application\Command\Auth\SignUpCommandHandler:
    tags: [ { name: messenger.message_handler, bus: command.bus } ]
    autoconfigure: false

  FC\Application\Command\Auth\SignInCommandHandler:
    tags: [ { name: messenger.message_handler, bus: command.bus } ]
    autoconfigure: false

  FC\Application\Command\Auth\RefreshTokenCommandHandler:
    tags: [ { name: messenger.message_handler, bus: command.bus } ]
    autoconfigure: false

  FC\Application\Command\Board\CreateBoardCommandHandler:
    tags: [ { name: messenger.message_handler, bus: command.bus } ]
    autoconfigure: false

  FC\Application\Command\Board\UpdateBoardCommandHandler:
    tags: [ { name: messenger.message_handler, bus: command.bus } ]
    autoconfigure: false

  FC\Application\Command\Board\RemoveBoardCommandHandler:
    tags: [ { name: messenger.message_handler, bus: command.bus } ]
    autoconfigure: false

  FC\Application\Command\Board\AddMemberCommandHandler:
    tags: [ { name: messenger.message_handler, bus: command.bus } ]
    autoconfigure: false

  FC\Application\Command\Board\RemoveMemberCommandHandler:
    tags: [ { name: messenger.message_handler, bus: command.bus } ]
    autoconfigure: false

  FC\Application\Command\Category\CreateCategoryCommandHandler:
    tags: [ { name: messenger.message_handler, bus: command.bus } ]
    autoconfigure: false

  FC\Application\Command\Category\UpdateCategoryCommandHandler:
    tags: [ { name: messenger.message_handler, bus: command.bus } ]
    autoconfigure: false

  FC\Application\Command\Category\RemoveCategoryCommandHandler:
    tags: [ { name: messenger.message_handler, bus: command.bus } ]
    autoconfigure: false

  FC\Application\Command\Tag\CreateTagCommandHandler:
    tags: [ { name: messenger.message_handler, bus: command.bus } ]
    autoconfigure: false

  FC\Application\Command\Tag\UpdateTagCommandHandler:
    tags: [ { name: messenger.message_handler, bus: command.bus } ]
    autoconfigure: false

  FC\Application\Command\Tag\RemoveTagCommandHandler:
    tags: [ { name: messenger.message_handler, bus: command.bus } ]
    autoconfigure: false

  FC\Application\Command\Card\CreateCardCommandHandler:
    tags: [ { name: messenger.message_handler, bus: command.bus } ]
    autoconfigure: false

  FC\Application\Command\Card\UpdateCardCommandHandler:
    tags: [ { name: messenger.message_handler, bus: command.bus } ]
    autoconfigure: false

  FC\Application\Command\Card\RemoveCardCommandHandler:
    tags: [ { name: messenger.message_handler, bus: command.bus } ]
    autoconfigure: false
