services:
  _defaults:
    autowire: true
    autoconfigure: true

  FC\Shared\Application\Command\CommandBus:
    class: FC\Shared\Infrastructure\Bus\SymfonyCommandBus
    arguments: [ '@command.bus' ]

  FC\Shared\Application\Query\QueryBus:
    class: FC\Shared\Infrastructure\Bus\SymfonyQueryBus
    arguments: [ '@query.bus' ]

  FC\Shared\Domain\Event\EventBus:
    class: FC\Shared\Infrastructure\Bus\SymfonyEventBus
    arguments: [ '@event.bus' ]
