services:
  _defaults:
    autowire: true
    autoconfigure: true

  FC\User\Domain\UserRepository:
    class: FC\User\Infrastructure\Repository\DoctrineUserRepository

  refresh_token.ttl:
    class: DateInterval
    arguments: [ '%env(REFRESH_TOKEN_TTL)%' ]

  access_token.ttl:
    class: DateInterval
    arguments: [ '%env(ACCESS_TOKEN_TTL)%' ]

  FC\User\Application\RefreshToken\RefreshTokenService:
    class: FC\User\Infrastructure\RefreshToken\Psr16RefreshTokenService
    arguments:
      $ttl: '@refresh_token.ttl'

  FC\User\Application\JWT\JWTEncoder:
    class: FC\User\Infrastructure\JWT\LcobucciJWTEncoder
    arguments:
      $ttl: '@access_token.ttl'

  FC\User\Application\JWT\JWTManagerInterface:
    class: FC\User\Application\JWT\JWTManager
    arguments:
      $identifierName: 'identifier'

  Symfony\Component\PasswordHasher\PasswordHasherInterface:
    class: Symfony\Component\PasswordHasher\Hasher\NativePasswordHasher

  FC\User\Application\Auth\AuthSessionServiceInterface:
    class: FC\User\Application\Auth\AuthSessionService

  FC\User\Application\Command\Create\CreateCommandHandler:
    tags: [ { name: messenger.message_handler, bus: command.bus } ]
    autoconfigure: false

  FC\User\Application\Command\SignIn\SignInCommandHandler:
    tags: [ { name: messenger.message_handler, bus: command.bus } ]
    autoconfigure: false

  FC\User\Application\Command\Refresh\RefreshTokenCommandHandler:
    tags: [ { name: messenger.message_handler, bus: command.bus } ]
    autoconfigure: false
