services:
  _defaults:
    autowire: true
    autoconfigure: true

  road_runner.jobs.consumer:
    class: Spiral\RoadRunner\Jobs\Consumer
    arguments:
      $worker: '@Spiral\RoadRunner\WorkerInterface'

  road_runner.jobs:
    class: Spiral\RoadRunner\Jobs\Jobs
    arguments:
      $rpc: '@goridge.rpc'

  Spiral\RoadRunner\Jobs\ConsumerInterface: '@road_runner.jobs.consumer'
  Spiral\RoadRunner\Jobs\JobsInterface: '@road_runner.jobs'
