rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php public/index.php"
  env:
    APP_RUNTIME: Runtime\RoadRunnerSymfonyNyholm\Runtime
    XDEBUG_SESSION: 1

http:
  address: 127.0.0.1:8080
  middleware: [ "headers", "gzip", "websockets" ]
  uploads:
    forbid: [ ".php", ".exe", ".bat", ".sh" ]
  headers:
    cors:
      allowed_origin: "http://localhost:1234"
      allowed_headers: "Content-Type,Accept,Authorization"
      allowed_methods: "GET,POST,PATCH,PUT,DELETE,OPTIONS"
      allow_credentials: true
#      exposed_headers: "*"
#      exposed_headers: "Cache-Control,Content-Language,Content-Type,Expires,Last-Modified,Pragma"
  pool:
    debug: true
    num_workers: 4
    max_jobs: 64

websockets:
  broker: "websockets"
  allowed_origin: "*"
  path: "/ws"
  pool:
    debug: true
    num_workers: 4
    max_jobs: 64

reload:
  services:
    http:
      dirs: [ "." ]
      recursive: true

kv:
  psr16:
    driver: memory
    config:
      interval: 1

broadcast:
  websockets:
    driver: memory
    config: { }
