web_controllers:
  resource: ../src/UI/Http/Web/Controller/
  type: annotation

rest_v1_controllers:
  resource: ../src/UI/Http/Rest/V1/Controller/
  type: annotation

kernel:
  resource: ../src/Infrastructure/Kernel.php
  type: annotation
